# Generated by Django 5.2.1 on 2025-05-16 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VC', 'Vice Chancellor'), ('REG', 'Registrar'), ('SA', 'Student Affairs'), ('SEC', 'Security Officer'), ('HW', 'Hall Warden'), ('WD', 'Works Department')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('MAIN', 'Maintenance Issues'), ('SAFE', 'Safety Issues'), ('CLASS', 'Lecture/Classroom Issues'), ('MISD', 'Misdemeanor Issues')], max_length=5)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MED', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRIT', 'Critical/Urgent')], max_length=4)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('REVW', 'Under Review'), ('ASSG', 'Assigned'), ('RESV', 'Resolved'), ('CLSD', 'Closed')], default='PEND', max_length=4)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_complaints', to='complaints.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='complaints.complaint')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='complaints.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='complaints.student'),
        ),
    ]
