# Generated by Django 5.2.1 on 2025-06-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='location_type',
            field=models.CharField(blank=True, choices=[('LECTURE', 'Lecture Room'), ('LAB', 'Laboratory'), ('LIBRARY', 'Library'), ('HOSTEL', 'Hostel'), ('CAFETERIA', 'Cafeteria'), ('SPORTS', 'Sports Facility'), ('ADMIN', 'Administrative Building'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
    ]
